version: "3.8"
services:
  mex-release:
    build:
      context: .
    ports:
      - 8081:8081
    environment:
      - MEX_RELEASE_HOST=0.0.0.0
      - MEX_RELEASE_PORT=8080
    expose:
      - 8081
    healthcheck:
      test: [ "CMD", "curl", "http://0.0.0.0:8080/_system/check" ]
      interval: 60s
      timeout: 5s
      retries: 5
    volumes:
      - data:/app/data
volumes:
  data:
